### PR TITLE
try to fix scrubbed absolute paths

### LINKED ISSUE #240: cleanup path rewriting
petsc records a huge amount of absolute paths in various places like petscvariables, etc., which are frequently incorrect in a conda situation, where runtime and build time regularly have no paths in common.

we try to fix some of these, but I think our fixes are introducing some of their own problems. In particular:

1. there shouldn't be any absolute paths recorded anywhere outside $PREFIX, certainly not for anything that is expected to exist at runtime
1. some `include` directories, e.g. `$cuda_incl`  are being rewritten as _not_ include directories (`$PREFIX`), meaning cuda include directories won't be preserved correctly
1. absolute paths to build tools are stored in variables like SED and MAKE. We relocate some of these to e.g. $PREFIX/bin/make which is _also_ wrong. I'm pretty sure that every reference to `anything/bin/$x` should be replaced with `$x` to let $PATH resolve it

### PR DESCRIPTION
**Pull request by minrk**
- replace $BUILD_PREFIX/bin/foo with foo so they resolve on $PATH, instead of hardcoding a patht hat won't exist (we did $PREFIX/bin before, but that is also wrong)
- leave cuda paths alone alone instead of rewriting $PREFIX/target/arch/include to $PREFIX, which is why slepc needed cuda includes
- dump petscvariables before/after for inspection/debugging

hopefully closes #240 

I was able to build cuda builds (both 11 and 12) of slepc locally with this, entirely removing the cuda stuff from slepc's build.sh, which I think is right

### CODE REVIEW

File: recipe/build.sh [hunk 1]
```diff
@@ -75,6 +75,7 @@ python ./configure \
   --COPTFLAGS="$CFLAGS -O3" \
   --CXXOPTFLAGS="$CXXFLAGS -O3" \
   --FOPTFLAGS="$FFLAGS -O3" \
+  --CUDAOPTFLAGS="-O3" \
```
Comment (minrk) [inline recipe/build.sh:78]: this doesn't change behavior, but preserves default behavior while suppressing a warning
